kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-template-hcl-config-map
data:
  config.hcl: |
    consul {
      address = "consul-consul-server.consul.svc.cluster.local:8500"
    }

    log_level = "info"

    template {
      source      = "/consul-template/templates/thanos-sd-file.tpl"
      destination = "/etc/thanos/sd/thanos-sd-file.yaml"
    }
