server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true

ui:
  enabled: true
  service:
    type: ClusterIP

client:
  enabled: true

connectInject:
  enabled: false

controller:
  enabled: false

dns:
  enabled: true

syncCatalog:
  enabled: true

