prometheus-node-exporter:
  hostPort: 9102
  containerPort: 9102
  service:
    port: 9102
    targetPort: 9102
    ports:
      - name: metrics
        port: 9102
        targetPort: 9102

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    retention: 2d

    externalLabels:
      cluster: singapore

    remoteWrite:
      - url: http://thanos-receive.monitoring.svc.cluster.local:19291/api/v1/receive
        name: thanos-receive
        # optional but recommended
        writeRelabelConfigs:
          - sourceLabels: [__name__]
            regex: ".*"
            action: keep

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

alertmanager:
  enabled: false

