prometheus-node-exporter:
  hostPort: 9102
  containerPort: 9102
  service:
    port: 9102
    targetPort: 9102
    ports:
      - name: metrics
        port: 9102
        targetPort: 9102

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    retention: 2d

    externalLabels:
      cluster: obserbility

    thanos:
      image: quay.io/thanos/thanos:v0.38.0
      #
      # Enable if use bucket
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-config
          key: objstore.yml

      grpcServerTlsConfig: {}   # nếu không dùng TLS

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

alertmanager:
  enabled: false

grafana:
  enabled: false  # false if install in monitored cluster
  adminPassword: "admin"
  service:
    type: NodePort  # Or LoadBalancer if need to expose to internet
  persistence:
    enabled: true
    storageClassName: standard  # hoặc storageClass phù hợp với cluster bạn
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard # Label của ConfigMap chứa dashboard
      searchNamespace: monitoring # Namespace tìm kiếm dashboard
      path: /etc/grafana/provisioning/dashboards

    datasources:
      enabled: true
      label: grafana_datasource # Label của ConfigMap chứa datasource
      searchNamespace: monitoring # Namespace tìm kiếm datasource
      path: /etc/grafana/provisioning/datasources
