type: GCS
config:
  bucket: "your-thanos-bucket-name"
  service_account: |
    {
      "type": "service_account",
      "project_id": "your-gcp-project-id",
      "private_key_id": "abc123...",
      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
      "client_email": "your-sa@your-project.iam.gserviceaccount.com",
      "client_id": "123456789...",
      ...
    }
