version: '3.7'

services:
  grafana:
    image: grafana/grafana:9.3.16
    user: root
    ports:
      - 6385:3000
    volumes:
      - /opt/grafana-data:/var/lib/grafana
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
