serviceAccount:
  create: true

networkPolicy:
  enabled: false

existingObjstoreSecret: thanos-objstore-config
existingObjstoreSecretItems:
  - key: objstore.yml
    path: objstore.yml

query:
  enabled: true
  replicaLabel: cluster
  stores:
    # - prometheus-operated.observer.svc.cluster.local:10901
    # - prometheus-operated.monitoring.svc.cluster.local:10901
    # - thanos-storegateway.monitoring.svc.cluster.local:10901

  grpcServer:
    service:
      type: ClusterIP

  httpServer:
    service:
      type: ClusterIP

storegateway:
  enabled: false
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 2Gi

compactor:
  enabled: false
  retention:
    resolutionRaw: 5d
    resolution5m: 30d
    resolution1h: 90d

  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 2Gi
