serviceAccount:
  create: true

networkPolicy:
  enabled: false

query:
  enabled: true
  replicaLabel: cluster
  stores:
    - prometheus-operated.monitoring.svc.cluster.local:10901

  storeEndpoints:
    - dnssrv+_grpc._tcp.prometheus-operated.monitoring.svc.cluster.local
    - dnssrv+_grpc._tcp.thanos-storegateway.monitoring.svc.cluster.local

  grpcServer:
    service:
      type: ClusterIP

  httpServer:
    service:
      type: ClusterIP

storegateway:
  enabled: true

  existingObjstoreSecret: thanos-objstore-config
  existingObjstoreSecretItems:
    - key: objstore.yml
      path: objstore.yml
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 2Gi

compactor:
  enabled: true

  existingObjstoreSecret: thanos-objstore-config
  existingObjstoreSecretItems:
    - key: objstore.yml
      path: objstore.yml

  retention:
    resolutionRaw: 5d
    resolution5m: 30d
    resolution1h: 90d

  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 600m
      memory: 2Gi
