serviceAccount:
  create: true

networkPolicy:
  enabled: false

existingObjstoreSecret: thanos-objstore-config
existingObjstoreSecretItems:
  - key: objstore.yml
    path: objstore.yml

query:
  enabled: true
  replicaLabel: cluster
  stores:
    - prometheus-operated.singapore.svc.cluster.local:10901

  grpcServer:
    service:
      type: ClusterIP

  httpServer:
    service:
      type: ClusterIP

queryFrontend:
  enabled: true
