# config: 
extraScrapeConfigs:
  - job_name: 'node-exporter'
    static_configs:
      # - targets: ['node-exporter.monitoring.svc:9100']
      - targets: ['node-exporter-prometheus-node-exporter.monitoring.svc.cluster.local:9100']

remoteWrite:
  - url: http://vmcluster-victoria-metrics-cluster-vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus

