adminPassword: 'admin' # Mật khẩu của tài khoản admin
service:
  type: NodePort  # Bạn có thể đổi sang LoadBalancer nếu cần truy cập ngoài
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard # Label của ConfigMap chứa dashboard
    searchNamespace: grafana # Namespace tìm kiếm dashboard
    path: /etc/grafana/provisioning/dashboards
  datasources:
    enabled: true
    label: grafana_datasource # Label của ConfigMap chứa datasource
    searchNamespace: grafana # Namespace tìm kiếm datasource
    path: /etc/grafana/provisioning/datasources
